USE jobportal;

SET @now = NOW();

INSERT INTO applicant_accounts (
    id, email, password, full_name, phone, bio, skills, experience, education, resume_url,
    created_at, updated_at
) VALUES
    (1, 'rohan.reddy1@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Rohan Reddy', '+91-9294181873', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Finance; Excel; Budgeting', '1-2 years', 'BBA', 'https://example.com/resume1.pdf', @now, @now),
    (2, 'isha.das2@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Isha Das', '+91-9491163514', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Data Science; TensorFlow; Statistics', '1-2 years', 'BBA', 'https://example.com/resume2.pdf', @now, @now),
    (3, 'aditya.khan3@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Aditya Khan', '+91-9907873857', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Customer Support; Zendesk; Escalations', '1-2 years', 'M.Tech Data Science', 'https://example.com/resume3.pdf', @now, @now),
    (4, 'meera.khan4@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Meera Khan', '+91-9968253265', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Customer Support; Zendesk; Escalations', '1-2 years', 'B.Des Communication', 'https://example.com/resume4.pdf', @now, @now),
    (5, 'tanya.singh5@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Tanya Singh', '+91-9595725097', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'UI/UX; Figma; Prototyping', '5+ years', 'M.Tech Data Science', 'https://example.com/resume5.pdf', @now, @now),
    (6, 'divya.das6@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Divya Das', '+91-9274008639', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Node.js; Express; MongoDB', '1-2 years', 'B.A. Economics', 'https://example.com/resume6.pdf', @now, @now),
    (7, 'isha.bose7@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Isha Bose', '+91-9616030284', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Digital Marketing; SEO; Content', 'Fresher', 'M.Tech Data Science', 'https://example.com/resume7.pdf', @now, @now),
    (8, 'ananya.khan8@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Ananya Khan', '+91-9190060226', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Python; Pandas; SQL', '3-4 years', 'BBA', 'https://example.com/resume8.pdf', @now, @now),
    (9, 'divya.reddy9@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Divya Reddy', '+91-9992329618', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Sales; Negotiation; CRM', 'Fresher', 'B.Com Finance', 'https://example.com/resume9.pdf', @now, @now),
    (10, 'nikhil.chatterjee10@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Nikhil Chatterjee', '+91-9475364113', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Java; Spring Boot; MySQL', '5+ years', 'B.Tech Computer Science', 'https://example.com/resume10.pdf', @now, @now),
    (11, 'kiran.verma11@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Kiran Verma', '+91-9501538092', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Node.js; Express; MongoDB', '5+ years', 'B.Sc. Information Technology', 'https://example.com/resume11.pdf', @now, @now),
    (12, 'lakshmi.iyer12@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Lakshmi Iyer', '+91-9130266145', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Digital Marketing; SEO; Content', 'Fresher', 'BHM', 'https://example.com/resume12.pdf', @now, @now),
    (13, 'arjun.kulkarni13@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Arjun Kulkarni', '+91-9256819248', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Python; Pandas; SQL', 'Fresher', 'B.A. Economics', 'https://example.com/resume13.pdf', @now, @now),
    (14, 'rahul.joshi14@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Rahul Joshi', '+91-9992398092', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Python; Pandas; SQL', '5+ years', 'BBA', 'https://example.com/resume14.pdf', @now, @now),
    (15, 'aditya.patel15@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Aditya Patel', '+91-9185068029', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Java; Spring Boot; MySQL', '3-4 years', 'B.Com Finance', 'https://example.com/resume15.pdf', @now, @now),
    (16, 'rohan.verma16@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Rohan Verma', '+91-9880862406', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Finance; Excel; Budgeting', '5+ years', 'B.Sc. Information Technology', 'https://example.com/resume16.pdf', @now, @now),
    (17, 'riya.iyer17@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Riya Iyer', '+91-9423358638', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'React; TypeScript; Redux', 'Fresher', 'B.Com Finance', 'https://example.com/resume17.pdf', @now, @now),
    (18, 'pooja.bose18@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Pooja Bose', '+91-9952442674', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Finance; Excel; Budgeting', '5+ years', 'B.Sc. Information Technology', 'https://example.com/resume18.pdf', @now, @now),
    (19, 'ananya.menon19@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Ananya Menon', '+91-9636687537', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Finance; Excel; Budgeting', 'Fresher', 'BHM', 'https://example.com/resume19.pdf', @now, @now),
    (20, 'divya.gupta20@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Divya Gupta', '+91-9359779090', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Python; Pandas; SQL', '3-4 years', 'BCA', 'https://example.com/resume20.pdf', @now, @now),
    (21, 'aarav.gupta21@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Aarav Gupta', '+91-9478833337', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Node.js; Express; MongoDB', '5+ years', 'MBA Marketing', 'https://example.com/resume21.pdf', @now, @now),
    (22, 'dev.verma22@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Dev Verma', '+91-9487195336', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'React; TypeScript; Redux', 'Fresher', 'BCA', 'https://example.com/resume22.pdf', @now, @now),
    (23, 'rahul.patel23@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Rahul Patel', '+91-9782546314', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Sales; Negotiation; CRM', '3-4 years', 'B.A. Economics', 'https://example.com/resume23.pdf', @now, @now),
    (24, 'aarav.mehta24@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Aarav Mehta', '+91-9946666926', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'React; TypeScript; Redux', '3-4 years', 'B.Com Finance', 'https://example.com/resume24.pdf', @now, @now),
    (25, 'ananya.kulkarni25@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Ananya Kulkarni', '+91-9724813934', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Digital Marketing; SEO; Content', '1-2 years', 'B.Tech Computer Science', 'https://example.com/resume25.pdf', @now, @now),
    (26, 'lakshmi.verma26@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Lakshmi Verma', '+91-9463512350', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Data Science; TensorFlow; Statistics', '1-2 years', 'BHM', 'https://example.com/resume26.pdf', @now, @now),
    (27, 'nikhil.joshi27@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Nikhil Joshi', '+91-9613818935', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Data Science; TensorFlow; Statistics', '1-2 years', 'MBA Marketing', 'https://example.com/resume27.pdf', @now, @now),
    (28, 'dev.joshi28@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Dev Joshi', '+91-9933428091', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Customer Support; Zendesk; Escalations', 'Fresher', 'B.A. Economics', 'https://example.com/resume28.pdf', @now, @now),
    (29, 'kabir.patel29@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Kabir Patel', '+91-9949447049', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Node.js; Express; MongoDB', 'Fresher', 'B.Des Communication', 'https://example.com/resume29.pdf', @now, @now),
    (30, 'riya.verma30@example.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Riya Verma', '+91-9527589822', 'Ambitious professional seeking to contribute to a high-growth organisation.', 'Project Management; Agile; JIRA', '5+ years', 'B.A. Economics', 'https://example.com/resume30.pdf', @now, @now);