USE jobportal;

SET @now = NOW();

INSERT INTO employer_accounts (
    id, email, password, contact_name, phone, company_name, company_description,
    company_website, company_location, created_at, updated_at
) VALUES
    (1, 'careers@tcs.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'TCS Talent Team', '+91-2267778000', 'Tata Consultancy Services', 'Global IT services and consulting leader headquartered in Mumbai.', 'https://www.tcs.com', 'Mumbai, IN', @now, @now),
    (2, 'talent@infosys.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Infosys People Team', '+91-8028502000', 'Infosys Limited', 'Digital services and consulting firm transforming businesses worldwide.', 'https://www.infosys.com', 'Bengaluru, IN', @now, @now),
    (3, 'careers@wipro.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Wipro Careers', '+91-8067446000', 'Wipro Limited', 'Leading technology services and consulting company.', 'https://www.wipro.com', 'Bengaluru, IN', @now, @now),
    (4, 'jobs@hcl.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'HCLTech Hiring', '+91-1204306000', 'HCLTech', 'Global technology company delivering IT and engineering services.', 'https://www.hcltech.com', 'Noida, IN', @now, @now),
    (5, 'talent@techmahindra.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Tech Mahindra HR', '+91-2042202222', 'Tech Mahindra', 'Connected world specialist providing IT and network services.', 'https://www.techmahindra.com', 'Pune, IN', @now, @now),
    (6, 'careers@larsentoubro.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'L&T Talent Acquisition', '+91-2244202000', 'Larsen & Toubro', 'Engineering and construction conglomerate with global presence.', 'https://www.larsentoubro.com', 'Mumbai, IN', @now, @now),
    (7, 'careers@ril.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Reliance HR', '+91-2222701000', 'Reliance Industries', 'Diverse conglomerate spanning energy, retail, and digital services.', 'https://www.ril.com', 'Mumbai, IN', @now, @now),
    (8, 'careers@icicibank.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'ICICI Bank HR', '+91-2266502500', 'ICICI Bank', 'Private sector bank offering retail and corporate banking services.', 'https://www.icicibank.com', 'Mumbai, IN', @now, @now),
    (9, 'careers@hdfcbank.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'HDFC Bank HR', '+91-2261606160', 'HDFC Bank', 'Leading private sector bank providing financial services.', 'https://www.hdfcbank.com', 'Mumbai, IN', @now, @now),
    (10, 'talent@kotak.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Kotak Hiring', '+91-2262106000', 'Kotak Mahindra Bank', 'Financial services group with banking, insurance, and investment arms.', 'https://www.kotak.com', 'Mumbai, IN', @now, @now),
    (11, 'careers@axisbank.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Axis Bank Careers', '+91-2264292525', 'Axis Bank', 'Private sector bank offering retail, SME, and corporate solutions.', 'https://www.axisbank.com', 'Mumbai, IN', @now, @now),
    (12, 'talent@sbi.co.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'SBI Talent Team', '+91-2234092020', 'State Bank of India', 'India’s largest public sector bank with global footprint.', 'https://www.sbi.co.in', 'Mumbai, IN', @now, @now),
    (13, 'careers@airtel.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Airtel HR', '+91-1244222222', 'Bharti Airtel', 'Telecommunications leader in mobile, broadband, and enterprise services.', 'https://www.airtel.in', 'Gurugram, IN', @now, @now),
    (14, 'talent@jio.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Jio Careers', '+91-2261204000', 'Reliance Jio', 'Digital services provider delivering 4G and broadband connectivity.', 'https://www.jio.com', 'Mumbai, IN', @now, @now),
    (15, 'careers@adityabirla.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Aditya Birla HR', '+91-2266515000', 'Aditya Birla Group', 'Global conglomerate with interests in metals, cement, and fashion.', 'https://www.adityabirla.com', 'Mumbai, IN', @now, @now),
    (16, 'talent@godrejinds.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Godrej Talent Team', '+91-2267675656', 'Godrej Industries', 'Diversified conglomerate spanning consumer goods, real estate, and chemicals.', 'https://www.godrejindustries.com', 'Mumbai, IN', @now, @now),
    (17, 'careers@hul.co.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'HUL Careers', '+91-2249832100', 'Hindustan Unilever', 'India’s largest fast-moving consumer goods company.', 'https://www.hul.co.in', 'Mumbai, IN', @now, @now),
    (18, 'talent@bajajauto.co.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Bajaj Auto HR', '+91-2047449585', 'Bajaj Auto', 'Leading manufacturer of two-wheelers and three-wheelers.', 'https://www.bajajauto.com', 'Pune, IN', @now, @now),
    (19, 'careers@tatasteel.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Tata Steel Talent', '+91-6576643333', 'Tata Steel', 'Steel manufacturing company serving global markets.', 'https://www.tatasteel.com', 'Jamshedpur, IN', @now, @now),
    (20, 'talent@mahindra.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Mahindra Careers', '+91-2222024000', 'Mahindra & Mahindra', 'Automotive and farm equipment multinational.', 'https://www.mahindra.com', 'Mumbai, IN', @now, @now),
    (21, 'careers@paytm.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Paytm Talent Team', '+91-1204770770', 'Paytm', 'Digital payments and financial services platform.', 'https://www.paytm.com', 'Noida, IN', @now, @now),
    (22, 'talent@swiggy.in', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Swiggy Careers', '+91-8067456000', 'Swiggy', 'On-demand delivery platform for food, groceries, and more.', 'https://www.swiggy.com', 'Bengaluru, IN', @now, @now),
    (23, 'careers@zomato.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Zomato Hiring', '+91-1244180777', 'Zomato', 'Food delivery and restaurant discovery platform.', 'https://www.zomato.com', 'Gurugram, IN', @now, @now),
    (24, 'talent@flipkart.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Flipkart Talent Team', '+91-8045460000', 'Flipkart', 'E-commerce marketplace serving millions of customers.', 'https://www.flipkart.com', 'Bengaluru, IN', @now, @now),
    (25, 'careers@byjus.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'BYJU''S Hiring', '+91-8039535000', 'BYJU''S', 'Edtech company offering personalised learning programmes.', 'https://www.byjus.com', 'Bengaluru, IN', @now, @now),
    (26, 'talent@phonepe.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'PhonePe Talent Team', '+91-8067679676', 'PhonePe', 'Digital payments platform enabling UPI and financial services.', 'https://www.phonepe.com', 'Bengaluru, IN', @now, @now),
    (27, 'careers@olacabs.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Ola Talent Team', '+91-8067399999', 'Ola', 'Ride-hailing and mobility platform operating across India.', 'https://www.olacabs.com', 'Bengaluru, IN', @now, @now),
    (28, 'talent@makemytrip.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'MakeMyTrip Careers', '+91-1244628700', 'MakeMyTrip', 'Online travel company offering flights, hotels, and holidays.', 'https://www.makemytrip.com', 'Gurugram, IN', @now, @now),
    (29, 'careers@nykaa.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'Nykaa Hiring', '+91-2249703300', 'Nykaa', 'Omnichannel beauty and lifestyle retailer.', 'https://www.nykaa.com', 'Mumbai, IN', @now, @now),
    (30, 'talent@bigbasket.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKC7jHimoMuqu', 'BigBasket Careers', '+91-8049154800', 'BigBasket', 'Online grocery delivery platform serving major Indian cities.', 'https://www.bigbasket.com', 'Bengaluru, IN', @now, @now);