USE jobportal;

SET @now = NOW();

INSERT INTO users (
    name, email, password, role, phone, bio, skills, experience, education, resume_url,
    company_name, company_description, company_website, company_location, created_at, updated_at
) VALUES
    ('Dev Reddy', 'dev.reddy1@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9294181873', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Finance; Excel; Budgeting', '1-2 years', 'BBA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Aarav Das', 'aarav.das2@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9491163514', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Node.js; Express; MongoDB', '5+ years', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Kiran Singh', 'kiran.singh3@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9351258749', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Project Management; Agile; JIRA', '1-2 years', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Kiran Singh', 'kiran.singh4@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9996696177', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Node.js; Express; MongoDB', '3-4 years', 'BBA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Meera Khan', 'meera.khan5@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9935504321', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Sales; Negotiation; CRM', '5+ years', 'MBA Marketing', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Pooja Iyer', 'pooja.iyer6@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9960345542', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Finance; Excel; Budgeting', '1-2 years', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Aarav Singh', 'aarav.singh7@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9498585961', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Project Management; Agile; JIRA', 'Fresher', 'M.Tech Data Science', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Pooja Sharma', 'pooja.sharma8@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9406084084', 'Ambitious professional seeking to contribute to a high-growth organization.', 'React; TypeScript; Redux', '1-2 years', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Meera Verma', 'meera.verma9@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9258214411', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Sales; Negotiation; CRM', 'Fresher', 'B.Com Finance', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Pooja Singh', 'pooja.singh10@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9475364113', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Java; Spring Boot; MySQL', '5+ years', 'B.Tech Computer Science', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Kabir Verma', 'kabir.verma11@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9501538092', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Node.js; Express; MongoDB', '5+ years', 'B.Sc. Information Technology', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Sneha Iyer', 'sneha.iyer12@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9130266145', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Digital Marketing; SEO; Content', 'Fresher', 'B.Des Communication', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Kiran Reddy', 'kiran.reddy13@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9247746438', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Java; Spring Boot; MySQL', '3-4 years', 'BBA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Lakshmi Reddy', 'lakshmi.reddy14@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9914799481', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Customer Support; Zendesk; Escalations', '5+ years', 'B.Tech Computer Science', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Nikhil Sharma', 'nikhil.sharma15@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9120405269', 'Ambitious professional seeking to contribute to a high-growth organization.', 'UI/UX; Figma; Prototyping', '1-2 years', 'MBA Marketing', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Vihaan Gupta', 'vihaan.gupta16@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9666690337', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Sales; Negotiation; CRM', 'Fresher', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Ananya Khan', 'ananya.khan17@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9230833665', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Java; Spring Boot; MySQL', '1-2 years', 'BCA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Arjun Gupta', 'arjun.gupta18@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9590822013', 'Ambitious professional seeking to contribute to a high-growth organization.', 'React; TypeScript; Redux', 'Fresher', 'BBA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Riya Verma', 'riya.verma19@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9117647321', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Project Management; Agile; JIRA', '1-2 years', 'MBA Marketing', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Rohan Das', 'rohan.das20@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9101679695', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Finance; Excel; Budgeting', '3-4 years', 'B.Com Finance', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Riya Das', 'riya.das21@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9301126777', 'Ambitious professional seeking to contribute to a high-growth organization.', 'React; TypeScript; Redux', '3-4 years', 'B.Sc. Information Technology', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Vihaan Verma', 'vihaan.verma22@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9644738967', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Project Management; Agile; JIRA', 'Fresher', 'BCA', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Pooja Singh', 'pooja.singh23@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9146744734', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Sales; Negotiation; CRM', '3-4 years', 'B.A. Economics', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Lakshmi Patel', 'lakshmi.patel24@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9483426624', 'Ambitious professional seeking to contribute to a high-growth organization.', 'React; TypeScript; Redux', '3-4 years', 'B.Com Finance', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('Lakshmi Sharma', 'lakshmi.sharma25@example.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'APPLICANT', '+91-9928393291', 'Ambitious professional seeking to contribute to a high-growth organization.', 'Finance; Excel; Budgeting', '3-4 years', 'MBA Marketing', 'https://example.com/resume.pdf', NULL, NULL, NULL, NULL, @now, @now),
    ('KKN Recruiters', 'hr@kknrecruiters.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'EMPLOYER', NULL, NULL, NULL, NULL, NULL, NULL, 'KKN Recruiters', 'Boutique hiring firm connecting top talent with innovative employers.', 'https://kknrecruiters.com', 'Bengaluru, IN', @now, @now),
    ('Nimbus Talent', 'careers@nimbustalent.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'EMPLOYER', NULL, NULL, NULL, NULL, NULL, NULL, 'Nimbus Talent', 'Full-service staffing partner for technology and operations teams.', 'https://nimbustalent.com', 'Hyderabad, IN', @now, @now),
    ('MetroSys HR', 'talent@metrosyshr.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'EMPLOYER', NULL, NULL, NULL, NULL, NULL, NULL, 'MetroSys HR', 'Supporting scaling startups with leadership and product hiring.', 'https://metrosyshr.com', 'Mumbai, IN', @now, @now),
    ('Sapphire Careers', 'jobs@sapphirecareers.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'EMPLOYER', NULL, NULL, NULL, NULL, NULL, NULL, 'Sapphire Careers', 'Matching professionals to finance, analytics, and IT roles since 2012.', 'https://sapphirecareers.com', 'Chennai, IN', @now, @now),
    ('Insight Recruit', 'hello@insightrecruit.com', '$2a$10$Dow1tK0N6D2PfYZ7RUTpuOZ4A3TBUnIF.rLnbryuVKy7jHimoMuqu', 'EMPLOYER', NULL, NULL, NULL, NULL, NULL, NULL, 'Insight Recruit', 'Talent acquisition specialists for product and consulting firms.', 'https://insightrecruit.com', 'Delhi, IN', @now, @now);